import type { Order, Product, User } from '@/types'

const now = () => new Date().toISOString()

export const DEMO_PASSWORD = '123456'

export const SHOP_NAME = 'SEDSP Tech Mall'

export const seedUsers: User[] = [
  {
    id: 'u-customer',
    email: 'customer@sedsp.vn',
    fullName: 'Nguyễn Văn Khách',
    role: 'customer',
    phone: '0901234567',
    address: '123 Lê Lợi, Q1, TP.HCM',
    createdAt: now(),
    active: true,
  },
  {
    id: 'u-seller',
    email: 'seller@sedsp.vn',
    fullName: 'Trần Thị Bán',
    role: 'seller',
    phone: '0912345678',
    createdAt: now(),
    active: true,
  },
  {
    id: 'u-manager',
    email: 'manager@sedsp.vn',
    fullName: 'Lê Văn Quản',
    role: 'manager',
    createdAt: now(),
    active: true,
  },
  {
    id: 'u-admin',
    email: 'admin@sedsp.vn',
    fullName: 'Phạm Admin',
    role: 'admin',
    createdAt: now(),
    active: true,
  },
]

export const seedPasswords: Record<string, string> = {
  'customer@sedsp.vn': DEMO_PASSWORD,
  'seller@sedsp.vn': DEMO_PASSWORD,
  'manager@sedsp.vn': DEMO_PASSWORD,
  'admin@sedsp.vn': DEMO_PASSWORD,
}

export const seedProducts: Product[] = [
  {
    id: 'p1',
    name: 'Tai nghe Bluetooth Pro ANC',
    description:
      'Tai nghe chống ồn chủ động, pin 30 giờ, hỗ trợ aptX HD. Bảo hành 12 tháng chính hãng.',
    price: 1_890_000,
    originalPrice: 2_490_000,
    stock: 45,
    category: 'Điện tử',
    imageUrl: 'https://picsum.photos/seed/p1/400/400',
    sellerId: 'u-seller',
    shopName: SHOP_NAME,
    shopLocation: 'TP.HCM',
    rating: 4.6,
    reviewCount: 89,
    soldCount: 128,
    isFlashSale: true,
    createdAt: now(),
  },
  {
    id: 'p2',
    name: 'Bàn phím cơ RGB KeyPro K87',
    description: 'Switch đỏ, khung nhôm, đèn RGB per-key, hot-swap switch.',
    price: 2_450_000,
    originalPrice: 2_990_000,
    stock: 22,
    category: 'Điện tử',
    imageUrl: 'https://picsum.photos/seed/p2/400/400',
    sellerId: 'u-seller',
    shopName: SHOP_NAME,
    shopLocation: 'TP.HCM',
    rating: 4.8,
    reviewCount: 56,
    soldCount: 89,
    createdAt: now(),
  },
  {
    id: 'p3',
    name: 'Áo thun cotton organic Unisex',
    description: '100% cotton hữu cơ, form regular fit, nhiều màu.',
    price: 289_000,
    originalPrice: 399_000,
    stock: 120,
    category: 'Thời trang',
    imageUrl: 'https://picsum.photos/seed/p3/400/400',
    sellerId: 'u-seller',
    shopName: 'SEDSP Fashion',
    shopLocation: 'Hà Nội',
    rating: 4.3,
    reviewCount: 142,
    soldCount: 256,
    createdAt: now(),
  },
  {
    id: 'p4',
    name: 'Giày chạy bộ AirFlex Marathon',
    description: 'Đế foam nhẹ, thoáng khí, phù hợp marathon và tập luyện hàng ngày.',
    price: 1_490_000,
    originalPrice: 1_990_000,
    stock: 8,
    category: 'Thể thao',
    imageUrl: 'https://picsum.photos/seed/p4/400/400',
    sellerId: 'u-seller',
    shopName: 'SEDSP Sport',
    shopLocation: 'Đà Nẵng',
    rating: 4.5,
    reviewCount: 38,
    soldCount: 67,
    isFlashSale: true,
    createdAt: now(),
  },
  {
    id: 'p5',
    name: 'Sách "Hệ thống hỗ trợ quyết định"',
    description: 'Giáo trình DSS cho sinh viên CNTT — NXB FPT.',
    price: 185_000,
    originalPrice: 220_000,
    stock: 50,
    category: 'Sách',
    imageUrl: 'https://picsum.photos/seed/p5/400/400',
    sellerId: 'u-seller',
    shopName: 'SEDSP Books',
    shopLocation: 'TP.HCM',
    rating: 4.9,
    reviewCount: 21,
    soldCount: 34,
    createdAt: now(),
  },
  {
    id: 'p6',
    name: 'Máy lọc không khí SmartAir H13',
    description: 'HEPA H13, cảm biến PM2.5, điều khiển app, phòng 30m².',
    price: 4_590_000,
    originalPrice: 5_490_000,
    stock: 15,
    category: 'Gia dụng',
    imageUrl: 'https://picsum.photos/seed/p6/400/400',
    sellerId: 'u-seller',
    shopName: SHOP_NAME,
    shopLocation: 'TP.HCM',
    rating: 4.7,
    reviewCount: 29,
    soldCount: 41,
    createdAt: now(),
  },
  {
    id: 'p7',
    name: 'Chuột gaming không dây X-Pro',
    description: 'Sensor 26K DPI, pin 70h, trọng lượng 59g, RGB tùy chỉnh.',
    price: 890_000,
    originalPrice: 1_190_000,
    stock: 60,
    category: 'Điện tử',
    imageUrl: 'https://picsum.photos/seed/p7/400/400',
    sellerId: 'u-seller',
    shopName: SHOP_NAME,
    shopLocation: 'TP.HCM',
    rating: 4.4,
    reviewCount: 73,
    soldCount: 198,
    isFlashSale: true,
    createdAt: now(),
  },
  {
    id: 'p8',
    name: 'Balo laptop chống nước 15.6"',
    description: 'Ngăn chống sốc, cổng USB sạc ngoài, chống nước IPX4.',
    price: 450_000,
    originalPrice: 590_000,
    stock: 35,
    category: 'Phụ kiện',
    imageUrl: 'https://picsum.photos/seed/p8/400/400',
    sellerId: 'u-seller',
    shopName: 'SEDSP Accessories',
    shopLocation: 'Cần Thơ',
    rating: 4.2,
    reviewCount: 44,
    soldCount: 112,
    createdAt: now(),
  },
  {
    id: 'p9',
    name: 'Nồi chiên không dầu 5L',
    description: 'Công nghệ Rapid Air, 8 chế độ nấu, dễ vệ sinh.',
    price: 1_290_000,
    originalPrice: 1_690_000,
    stock: 28,
    category: 'Gia dụng',
    imageUrl: 'https://picsum.photos/seed/p9/400/400',
    sellerId: 'u-seller',
    shopName: SHOP_NAME,
    shopLocation: 'TP.HCM',
    rating: 4.6,
    reviewCount: 67,
    soldCount: 156,
    createdAt: now(),
  },
  {
    id: 'p10',
    name: 'Kính râm polarized UV400',
    description: 'Gọng TR90 siêu nhẹ, tròng polarized chống chói.',
    price: 320_000,
    originalPrice: 450_000,
    stock: 80,
    category: 'Thời trang',
    imageUrl: 'https://picsum.photos/seed/p10/400/400',
    sellerId: 'u-seller',
    shopName: 'SEDSP Fashion',
    shopLocation: 'Hà Nội',
    rating: 4.1,
    reviewCount: 31,
    soldCount: 88,
    createdAt: now(),
  },
]

export const seedOrders: Order[] = [
  {
    id: 'o1',
    customerId: 'u-customer',
    customerName: 'Nguyễn Văn Khách',
    items: [
      {
        productId: 'p1',
        productName: 'Tai nghe Bluetooth Pro ANC',
        quantity: 1,
        unitPrice: 1_890_000,
      },
    ],
    total: 1_890_000,
    status: 'delivered',
    shippingAddress: '123 Lê Lợi, Q1, TP.HCM',
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: now(),
  },
  {
    id: 'o2',
    customerId: 'u-customer',
    customerName: 'Nguyễn Văn Khách',
    items: [
      {
        productId: 'p3',
        productName: 'Áo thun cotton organic Unisex',
        quantity: 2,
        unitPrice: 289_000,
      },
    ],
    total: 578_000,
    status: 'shipping',
    shippingAddress: '123 Lê Lợi, Q1, TP.HCM',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: now(),
  },
]
